








CREATE OR REPLACE TABLE {{params.reports}}.TEMP_TABLE (
    TRANSFER_ID NUMBER,CHANGE_TYPE VARCHAR,ACTION_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
     PAYOUT_CLASSIFICATION VARCHAR);


INSERT INTO {{params.reports}}.TEMP_TABLE (TRANSFER_ID, CHANGE_TYPE, PAYOUT_CLASSIFICATION)
VALUES (508608673,'PAYOUT_CLASSIFICATION','DBO');




-- SELECT
-- CONCAT('INSERT INTO {{params.reports}}.TEMP_TABLE (TRANSFER_ID, CHANGE_TYPE, PAYOUT_CLASSIFICATION) VALUES (',
--     TRANSFER_ID,',','''','PAYOUT_CLASSIFICATION','''',',','''',PAYOUT_CLASSIFICATION,'''',')')
-- FROM SANDBOX_DB.SANDBOX_NUMAIR_FAZILI.PKR_CHANGE_LOG
-- order by PAYOUT_CLASSIFICATION


SELECT
*
    FROM {{params.reports}}.PKR_CLASSIFICATION