CREATE OR REPLACE TABLE {{params.reports}}.PKR_CHANGE_LOG (
    TRANSFER_ID NUMBER,CHANGE_TYPE VARCHAR,ACTION_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
     PAYOUT_CLASSIFICATION VARCHAR, TRANSFER_STATE VARCHAR, RECOVERY_SOURCE VARCHAR,
     RECOVERY_CURRENCY VARCHAR,RECOVERY_AMOUNT DOUBLE,NOTIFIED_FLAG BOOLEAN, RECOVERED_FLAG BOOLEAN);

