

-- BUSINESS CUSTOMERS WHO TRIGGERED VERIFICATION (BY ORDERING ACCOUNT DETAILS)
WITH USERS_REQUEST_VERIFICATION AS (
SELECT
    DISTINCT VOD.PROFILE_ID, USER_PROFILE_CREATED,COUNTRY_CODE_3_CHAR,UPPER(CUSTOMER_CLASS) AS CUSTOMER_CLASS,
    COUNT(DISTINCT VOD.PROFILE_ID) OVER(PARTITION BY COUNTRY_CODE_3_CHAR,CUSTOMER_CLASS) AS TOTALCOUNT,
    COMPANY_TYPE,SECOND_LEVEL_CATEGORY,COUNT(DISTINCT CBG.PROFILE_ID) OVER(PARTITION BY COUNTRY_CODE_3_CHAR,CUSTOMER_CLASS) AS TOTALBUSINESSCOUNT
FROM ANALYTICS_DB.REPORTS.RECEIVE_ACCOUNT_DETAILS_ACTIVATION_FUNNEL AS VOD
    INNER JOIN REPORTS.REGIONAL_USER_PROFILE_CHARACTERISTICS UP
        ON UP.USER_PROFILE_ID = VOD.PROFILE_ID
    LEFT JOIN REPORTS.COMPLIANCE_BUSINESSES_GENERAL CBG
        ON CBG.PROFILE_ID = UP.USER_PROFILE_ID
WHERE TRUE
AND UPPER(UP.COUNTRY_CODE_3_CHAR) IN ('IND','MYS','PHL','IDN')
AND VOD.FIRST_ACCOUNT_DETAILS_ORDER_TIME IS NOT NULL
AND PROFILE_CREATION_TIME >= '2022-08-01')


SELECT
UPPER(COUNTRY_CODE_3_CHAR),
LISTAGG(DISTINCT VERIFICATION_REGION,',')  AS VERIFICATION_REGIONS,
ROUND(MEDIAN(HANDLING_TIME_MINUTES),2) AS MEDIAN_HT,
ROUND(AVG(HANDLING_TIME_MINUTES),2) AS AVG_HT,
ROUND(SUM(VUC.COST)) AS TOTAL_VERIFICATION_COST,
ROUND(SUM(VUC.COST) /COUNT(DISTINCT VCM.USER_PROFILE_ID), 2) AS AVG_COSTS,
ROUND(COUNT(VCM.USER_PROFILE_ID)/COUNT(DISTINCT VCM.USER_PROFILE_ID),2) AS AVG_VERIFICATION_STEPS,
COUNT(DISTINCT VCM.USER_PROFILE_ID) AS COUNT_PROFILES
FROM REPORTS.VERIFICATION_COST_MANUAL_SPLIT_BY_TIME VCM
INNER JOIN USERS_REQUEST_VERIFICATION URV
    ON URV.PROFILE_ID = VCM.USER_PROFILE_ID
    INNER JOIN REPORTS.VERIFICATION_USER_COST VUC
        ON VUC.VERIFICATION_ID =  VCM.VERIFICATION_ID
WHERE TRUE
AND UPPER(COUNTRY_CODE_3_CHAR) IN ('IND','MYS','PHL','IDN')
AND UPPER(CUSTOMER_CLASS) = 'BUSINESS'
AND USER_PROFILE_CREATED >= '2022-08-01'
GROUP BY 1;

--SAME CTE AS ABOVE
WITH USERS_REQUEST_VERIFICATION AS (
SELECT
    DISTINCT VOD.PROFILE_ID, USER_PROFILE_CREATED,COUNTRY_CODE_3_CHAR,UPPER(CUSTOMER_CLASS) AS CUSTOMER_CLASS,
    COUNT(DISTINCT VOD.PROFILE_ID) OVER(PARTITION BY COUNTRY_CODE_3_CHAR,CUSTOMER_CLASS) AS TOTALCOUNT,
    COMPANY_TYPE,SECOND_LEVEL_CATEGORY,COUNT(DISTINCT CBG.PROFILE_ID) OVER(PARTITION BY COUNTRY_CODE_3_CHAR,CUSTOMER_CLASS) AS TOTALBUSINESSCOUNT
FROM ANALYTICS_DB.REPORTS.RECEIVE_ACCOUNT_DETAILS_ACTIVATION_FUNNEL AS VOD
    INNER JOIN REPORTS.REGIONAL_USER_PROFILE_CHARACTERISTICS UP
        ON UP.USER_PROFILE_ID = VOD.PROFILE_ID
    LEFT JOIN REPORTS.COMPLIANCE_BUSINESSES_GENERAL CBG
        ON CBG.PROFILE_ID = UP.USER_PROFILE_ID
WHERE TRUE
AND UPPER(UP.COUNTRY_CODE_3_CHAR) IN ('IND','MYS','PHL','IDN')
AND VOD.FIRST_ACCOUNT_DETAILS_ORDER_TIME IS NOT NULL
AND PROFILE_CREATION_TIME >= '2022-08-01')

SELECT
COUNT(DISTINCT USER_PROFILE_ID),
ROUND(SUM(VERIFICATION)) AS TOTAL_VERIFICATION_COST,
ROUND(SUM(VERIFICATION) / COUNT(DISTINCT USER_PROFILE_ID),2) AVG_VERIFICATION_COST
FROM REPORTS.CUSTOMER_ECON_DATASET_PUBLIC CE
INNER JOIN USERS_REQUEST_VERIFICATION UR
    ON UR.PROFILE_ID = CE.USER_PROFILE_ID
WHERE TRUE
AND CUSTOMER_CLASS = 'BUSINESS'
AND COUNTRY_CODE_3_CHAR = 'IND'
AND PERIOD_START >= '2022-8-01'
AND VERIFICATION!=0;  -- ONLY THOSE USERS WHO HAD VERIFICATION COST (OTHERWISE AVERAGE WILL BE SKEWED)


/*
 EXAMPLE

 OBTAINING VERIFICATION COST FOR CST (33189489) FROM VERIFICATION_USER_COST AND HANDLING TIME FROM VERIFICATION_COST_MANUAL_SPLIT_BY_TIME.
 */

SELECT * FROM REPORTS.VERIFICATION_COST_MANUAL_SPLIT_BY_TIME VCM
    INNER JOIN REPORTS.VERIFICATION_USER_COST VUC
        ON VUC.VERIFICATION_ID =  VCM.VERIFICATION_ID
WHERE VCM.USER_PROFILE_ID = 33189489;

/*
 COMPARING VERIFICATION COSTS B/W CUSTOMER ECONOMICS AND VERIFICATION_USER_COST

 1. INCORRECT PRODUCT CLASSIFICATION (MINOR)
 2. VERIFICATION COST DOES NOT MATCH WITH VERIFICATION_USER_COST TABLE 9.93 IN CE VS 4.36 IN VUC
 */


SELECT * FROM REPORTS.CUSTOMER_ECON_DATASET_PUBLIC WHERE USER_PROFILE_ID = 33189489;